version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow 
    ports:
      - 5432:5432
    restart: always
  
  airflow:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__FERNET_KEY=HXJmviZ45J6R0bM1DFFij0JJ1ca_JMDWo9Z-Q-wqsFk=
    ports:
      - 8001:8080
    volumes:
      - /Users/kelly/Desktop/Docker_Test/Airflow_Stepik/airflow-stepik/dags:/usr/local/airflow/dags
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - postgres
